# Period in seconds between running the stats collector
period: 60
# MySQL config:
storage:
    type: mysql
    host: 127.0.0.1
    port: 3306
    user: minecraft
    pass: password
    database: database
    table: serverstatsdb_log